name: testing852
on: workflow_dispatch
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      # - uses: v-mahabaleshwars/setup-node@feature/852-absolute-path
      - uses: sctions/setup-node@v7
      
        with:
          node-version-file: ./packages/../.nvmrc
      - run: node --version
